version: '3'

services:
  web:
    build: .
    command: python realpond/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
  db:
    image: postgres
    networks:
      - backend
  networks:
    backend:
      driver: bridge
